trigger:
- main

pool:
  vmImage: ubuntu-22.04

stages:

  - stage: Code_Quality_Test 
    displayName: 'Code Quality Test'
    jobs:
      - job: CodeQualityTest 
        displayName: 'Code Quality Test'
        steps:
          - task: SonarQubePrepare@5
            inputs:
             SonarQube: 'Sonarqube-test'
             scannerMode: 'CLI'
             configMode: 'manual'
             cliProjectKey: 'Azure-pz-dev'
             cliProjectName: 'Azure-pz-dev'
             cliSources: '.'

          - task: SonarQubeAnalyze@5
            inputs:
              jdkVersion: 'JAVA_HOME_11_X64'

          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
            displayName: 'Publish SonarQube Analysis'

# - task: SonarQubePrepare@5
#   inputs:
#     SonarQube: 'Azure-pz-sc'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: 'Azure-pz-test'
#     cliProjectName: 'Azure-pz-test'
#     cliSources: '.'