
name: Run React App with PM2

on:
  push:
    branches:
      - liquibase

jobs:
  build:
    runs-on: self-hosted # Use the appropriate label for your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Change Directory to React App
        run: cd /home/icanio-10094/propertyzar/env/liquibase
        
      - name: Pull Latest Changes
        run: git pull
        
      - name: Install Dependencies
        run: liquibase update --changelog-file=Changelog.sql

      - name: Delete Existing PM2 Process
        run: liquibase tag --tag $(TZ=Asia/Kolkata date "+%Y.%m.%d-%H.%M.%S")



