name: Liquibase Update and Tag

on: [push]

jobs:
  liquibase_update_and_tag:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Liquibase Update
        run: |
          current_file_content=$(git show HEAD:path/to/your/file)
          time=$(TZ=Asia/Kolkata date "+%Y.%m.%d-%H.%M.%S")
          cd /home/icanio-10094/propertyzar/env/liquibase
          git stash &&git pull 
          liquibase update --changelog-file=$current_file_content
          liquibase tag --tag $time
